name: Rust Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write

env:
  CARGO_TERM_COLOR: always
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Needed
      run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Buildable
      run: cargo build --verbose --features dev
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Needed
      run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: LoliGothick/clippy-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allow: >
          nonstandard_macro_braces
          mutex_atomic
        deny: warnings
#  quality:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Install Needed
#      run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
#    - name: Run Clippy
#      run: cargo clippy --all-targets --all-features
