name: Buildable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Needed
      run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Buildable
      run: cargo build --verbose --features dev
#  quality:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Install Needed
#      run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
#    - name: Run Clippy
#      run: cargo clippy --all-targets --all-features
