on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Needed
        run: sudo apt-get install -y -qq librust-alsa-sys-dev pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features